### ISSUE TITLE
join-domain formula fail if stig baseline has already been applied

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-windows-formula#22]
Need to find the setting that is causing the failure.

**Comment by ferricoxide** [comment]
As part of closing other issues, have been running the join-domain formula without incident on hardened systems. Was this a Windows-only issue?

**Comment by lorengordon** [comment]
Fixed by https://github.com/plus3it/join-domain-formula/commit/de4d6294666e20e528d3950180affc565032095e
