### ISSUE TITLE
Write custom 'lgpo' state module to manage the custom 'lgpo' execution module

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-windows-formula#25]

**Comment by ferricoxide** [comment]
Is there a description that can be provided, here, that might allow someone else to take a stab at the problem?

**Comment by lorengordon** [comment]
I'm happy to try to describe it, but I feel like I'll need to talk through it a few times before I can write it out. It's a little involved, especially for someone who may not already be familiar with salt and salt state modules.

**Comment by ferricoxide** [comment]
No worries. Just trying to foster task-delegability :)

**Comment by lorengordon** [comment]
Closed by #27
