### ISSUE TITLE
Update `lgpo` custom python modules to use the newer LGPO.exe utility

### ISSUE THREAD

**Issue by lorengordon** [plus3it/ash-windows-formula#29]
Link: https://blogs.technet.microsoft.com/secguide/2016/01/21/lgpo-exe-local-group-policy-object-utility-v1-0/

This would replace the older Apply_LGPO_Delta.exe utility.

**Comment by Phydeauxman** [comment]
Below is where the latest version of LGPO can be obtained from:
https://www.microsoft.com/en-us/download/details.aspx?id=55319
