### ISSUE TITLE
V-26580 | WN12-CC-000085 | SV-52965r2_rule doesn't appear to be applying the correct value

### ISSUE THREAD

**Issue by ewierschke** [plus3it/ash-windows-formula#43]
The following check appears to be setting an incorrect value compared to the check text.
V-26580 | WN12-CC-000085 | SV-52965r2_rule
The check text states:
Type: REG_DWORD
Value: 0x00030000 (196608) (or greater)

But the application of ash-windows-formula appears to set (81920).  
The SCAP scan also incorrectly passes the check based on its value check of 81920 instead of 196608.

**Comment by lorengordon** [comment]
We generally only check against the SCAP content. If the SCAP content is incorrect, then the issue is upstream with DISA. We wouldn't fix this until the SCAP content is updated and reports the failure.
